#!/bin/sh

[ -e ../../tests.sh ] && . ../../tests.sh

NAME="PT5 3"
FILE=../../bins/forArdour.pts
EXPECT='ProTools 5 Session: Samplerate = 48000Hz
Target samplerate = 48000

6 wavs, 6 regions, 6 active regions

Audio file (WAV#) @ offset, length:
`bass_01.L` w(0) @ 0, 1758775
`bass_01.R` w(1) @ 0, 1758775
`rhodes_01.R` w(2) @ 0, 1528453
`rhodes_01.L` w(3) @ 0, 1528453
`oerc_01.R` w(4) @ 0, 1643572
`oerc_01.L` w(5) @ 0, 1643572

Region (Region#) (WAV#) @ into-sample, length:
`bass_01.L` r(0) w(0) @ 0, 1758775
`bass_01.R` r(1) w(1) @ 0, 1758775
`oerc_01.L` r(2) w(5) @ 0, 1643572
`oerc_01.R` r(3) w(4) @ 0, 1643572
`rhodes_01.L` r(4) w(3) @ 0, 1528453
`rhodes_01.R` r(5) w(2) @ 0, 1528453

MIDI Region (Region#) @ into-sample, length:

Track name (Track#) (Region#) @ Absolute:
`rhodes` t(0) r(4) @ 0
`rhodes` t(1) r(5) @ 0
`bass` t(2) r(0) @ 0
`bass` t(3) r(1) @ 0
`oerc` t(4) r(2) @ 0
`oerc` t(5) r(3) @ 0

MIDI Track name (MIDITrack#) (MIDIRegion#) @ Absolute:

Track name (Track#) (WAV filename) @ Absolute + Into-sample, Length:
`rhodes` t(0) (rhodes_01.L) @ 0 + 0, 1528453
`rhodes` t(1) (rhodes_01.R) @ 0 + 0, 1528453
`bass` t(2) (bass_01.L) @ 0 + 0, 1758775
`bass` t(3) (bass_01.R) @ 0 + 0, 1758775
`oerc` t(4) (oerc_01.L) @ 0 + 0, 1643572
`oerc` t(5) (oerc_01.R) @ 0 + 0, 1643572'

run_test
