#!/bin/sh

[ -e ../../tests.sh ] && . ../../tests.sh

NAME="PT5 1"
FILE=../../bins/Damien_monos.pts
EXPECT='ProTools 5 Session: Samplerate = 48000Hz
Target samplerate = 48000

8 wavs, 8 regions, 8 active regions

Audio file (WAV#) @ offset, length:
`Bass_L_01.aif` w(0) @ 0, 0
`Bass_R_01.aif` w(1) @ 0, 0
`cymb_L_01.aif` w(2) @ 0, 0
`cymb_R_01.aif` w(3) @ 0, 0
`DR_L.aif` w(4) @ 0, 0
`DR_R.aif` w(5) @ 0, 0
`Rhodes_L_01.aif` w(6) @ 0, 0
`Rhodes_R_01.aif` w(7) @ 0, 0

Region (Region#) (WAV#) @ into-sample, length:
`DR_L` r(0) w(4) @ 0, 1377004
`DR_R` r(1) w(5) @ 0, 1377004
`Rhodes_L` r(2) w(6) @ 0, 1377004
`Rhodes_R` r(3) w(7) @ 0, 1377004
`Bass_L` r(4) w(0) @ 0, 1377004
`Bass_R` r(5) w(1) @ 0, 1377004
`cymb_L` r(6) w(2) @ 0, 1355463
`cymb_R` r(7) w(3) @ 0, 1355463

MIDI Region (Region#) @ into-sample, length:

Track name (Track#) (Region#) @ Absolute:
`DR_L` t(1) r(0) @ 0
`DR_R` t(2) r(1) @ 0
`Rhodes_L` t(3) r(2) @ 0
`Rhodes_R` t(4) r(3) @ 0
`Bass_L` t(5) r(4) @ 0
`Bass_R` t(6) r(5) @ 0
`cymb_L` t(7) r(6) @ 0
`cymb_R` t(8) r(7) @ 0

MIDI Track name (MIDITrack#) (MIDIRegion#) @ Absolute:

Track name (Track#) (WAV filename) @ Absolute + Into-sample, Length:
`DR_L` t(1) (DR_L.aif) @ 0 + 0, 1377004
`DR_R` t(2) (DR_R.aif) @ 0 + 0, 1377004
`Rhodes_L` t(3) (Rhodes_L_01.aif) @ 0 + 0, 1377004
`Rhodes_R` t(4) (Rhodes_R_01.aif) @ 0 + 0, 1377004
`Bass_L` t(5) (Bass_L_01.aif) @ 0 + 0, 1377004
`Bass_R` t(6) (Bass_R_01.aif) @ 0 + 0, 1377004
`cymb_L` t(7) (cymb_L_01.aif) @ 0 + 0, 1355463
`cymb_R` t(8) (cymb_R_01.aif) @ 0 + 0, 1355463'

run_test
